### ISSUE TITLE
Failed to Run Seralization weaver with command...

### ISSUE THREAD

**Issue by dtmnash** [SaladLab/Json.Net.Unity3D#12]
I love JSON.NET and am excited that someone has brought it to Unity3d. I'm using the Unity HoloLens Technical Preview 5.4.0f3-HTP and version 8.0.3 JSON.NET/JSON.NET.Unity3D

I had to use the workaround you've published for UWP apps but I keep running into a runtime exception when trying to parse an OData response to a model I built that represents the response.

Would appreciate your thoughts/suggestions.

Warning: unknown type System.AsyncCallback detected. Using reflection to gather its type information. Consider to reference it from your scripts so it can gathered during the build process.

(Filename: C:\buildslave\unity\build\Runtime/Scripting/Backend/DotNet/ScriptingTypeProvider_DotNet.cpp Line: 153)

Exception thrown: 'System.InvalidOperationException' in mscorlib.ni.dll
InvalidOperationException: Handle is not initialized.
   at System.Runtime.InteropServices.GCHandle.FromIntPtr(IntPtr value)
   at UnityEngine.Internal.$MethodUtility.CreateInstanceAndInvokeDefaultConstructor(IntPtr type, UIntPtr argument0, Int64\* argument1)
   at UnityEngineProxy.InternalCalls.PInvokeCalls.JsonUtility_CUSTOM_FromJson(IntPtr param_0, Int32 param_1)
   at UnityEngineProxy.InternalCalls.JsonUtility_CUSTOM_FromJson(String json, Type type)
   at UnityEngine.JsonUtility.FromJson[T](String json)
   at ShowDataOnGaze.<GetData>d__3.MoveNext()
   at UnityEngine.SetupCoroutine.InvokeMoveNext(IEnumerator enumerator, IntPtr returnValueAddress)
   at UnityEngine.SetupCoroutine.$Invoke1InvokeMoveNext(Int64 instance, Int64\* args)
   at UnityEngine.Internal.$MethodUtility.InvokeMethod(Int64 instance, Int64\* args, IntPtr method) 
(Filename: <Unknown> Line: 0)

**Comment by deniesposito** [comment]
Any luck finding a solution?

**Comment by veblush** [comment]
@dtmnash From your callstack, there is a call to [JsonUtility.FromJson](https://docs.unity3d.com/ScriptReference/JsonUtility.FromJson.html) which is not one of Json.Net but UnityEngine. Is it right callstack?

**Comment by deniesposito** [comment]
I am not sure if this helps but I am also using your library and I have the following error. 

UnityException: Failed to run serialization weaver with command "Temp\StagingArea\Data\Managed\Newtonsoft.Json.dll" -pdb -verbose -unity-engine="Temp\StagingArea\Data\Managed\UnityEngine.dll" "Temp\StagingArea\TempSerializationWeaver" -lock=UWP\project.lock.json -additionalAssemblyPath="Temp\StagingArea\Data\Managed" -additionalAssemblyPath="Temp\StagingArea\Data\Managed\Plugins\X86" -additionalAssemblyPath="C:\Program Files (x86)\Windows Kits\10\UnionMetadata\Facade" -additionalAssemblyPath="C:\Program Files (x86)\Windows Kits\10\References\Windows.ApplicationModel.Calls.CallsVoipContract\1.0.0.0" -additionalAssemblyPath="C:\Program Files (x86)\Windows Kits\10\References\Windows.ApplicationModel.SocialInfo.SocialInfoContract\1.0.0.0" -additionalAssemblyPath="C:\Program Files (x86)\Windows Kits\10\References\Windows.Devices.DevicesLowLevelContract\2.0.0.0" -additionalAssemblyPath="C:\Program Files (x86)\Windows Kits\10\References\Windows.Devices.Printers.PrintersContract\1.0.0.0" -additionalAssemblyPath="C:\Program Files (x86)\Windows Kits\10\References\Windows.Foundation.FoundationContract\2.0.0.0" -additionalAssemblyPath="C:\Program Files (x86)\Windows Kits\10\References\Windows.Foundation.UniversalApiContract\3.0.0.0" -additionalAssemblyPath="C:\Program Files (x86)\Windows Kits\10\References\Windows.Graphics.Printing3D.Printing3DContract\3.0.0.0" -additionalAssemblyPath="C:\Program Files (x86)\Windows Kits\10\References\Windows.Networking.Connectivity.WwanContract\1.0.0.0" -additionalAssemblyPath="C:\Program Files (x86)\Windows Kits\10\References\Windows.Services.Store.StoreContract\1.0.0.0" -additionalAssemblyPath="C:\Program Files (x86)\Windows Kits\10\References\Windows.System.Profile.ProfileHardwareTokenContract\1.0.0.0" -additionalAssemblyPath="C:\Program Files (x86)\Windows Kits\10\References\Windows.System.Profile.ProfileSharedModeContract\1.0.0.0" -additionalAssemblyPath="C:\Program Files (x86)\Windows Kits\10\References\Windows.UI.ViewManagement.ViewManagementViewScalingContract\1.0.0.0" -additionalAssemblyPath="C:\Program Files (x86)\Windows Kits\10\References\Windows.ApplicationModel.Activation.ActivatedEventsContract\1.0.0.0" -additionalAssemblyPath="C:\Program Files (x86)\Windows Kits\10\References\Windows.ApplicationModel.Activation.ActivationCameraSettingsContract\1.0.0.0" -additionalAssemblyPath="C:\Program Files (x86)\Windows Kits\10\References\Windows.ApplicationModel.Activation.ContactActivatedEventsContract\1.0.0.0" -additionalAssemblyPath="C:\Program Files (x86)\Windows Kits\10\References\Windows.ApplicationModel.Activation.WebUISearchActivatedEventsContract\1.0.0.0" -additionalAssemblyPath="C:\Program Files (x86)\Windows Kits\10\References\Windows.ApplicationModel.Background.BackgroundAlarmApplicationContract\1.0.0.0" -additionalAssemblyPath="C:\Program Files (x86)\Windows Kits\10\References\Windows.ApplicationModel.Calls.Background.CallsBackgroundContract\1.0.0.0" -additionalAssemblyPath="C:\Program Files (x86)\Windows Kits\10\References\Windows.ApplicationModel.Calls.LockScreenCallContract\1.0.0.0" -additionalAssemblyPath="C:\Program Files (x86)\Windows Kits\10\References\Windows.ApplicationModel.FullTrustAppContract\1.0.0.0" -additionalAssemblyPath="C:\Program Files (x86)\Windows Kits\10\References\Windows.ApplicationModel.Preview.Notes.PreviewNotesContract\1.0.0.0" -additionalAssemblyPath="C:\Program Files (x86)\Windows Kits\10\References\Windows.ApplicationModel.Resources.Management.ResourceIndexerContract\1.0.0.0" -additionalAssemblyPath="C:\Program Files (x86)\Windows Kits\10\References\Windows.ApplicationModel.Search.Core.SearchCoreContract\1.0.0.0" -additionalAssemblyPath="C:\Program Files (x86)\Windows Kits\10\References\Windows.ApplicationModel.Search.SearchContract\1.0.0.0" -additionalAssemblyPath="C:\Program Files (x86)\Windows Kits\10\References\Windows.ApplicationModel.StartupTaskContract\1.0.0.0" -additionalAssemblyPath="C:\Program Files (x86)\Windows Kits\10\References\Windows.ApplicationModel.Wallet.WalletContract\1.0.0.0" -additionalAssemblyPath="C:\Program Files (x86)\Windows Kits\10\References\Windows.Devices.Custom.CustomDeviceContract\1.0.0.0" -additionalAssemblyPath="C:\Program Files (x86)\Windows Kits\10\References\Windows.Devices.Portable.PortableDeviceContract\1.0.0.0" -additionalAssemblyPath="C:\Program Files (x86)\Windows Kits\10\References\Windows.Devices.Printers.Extensions.ExtensionsContract\2.0.0.0" -additionalAssemblyPath="C:\Program Files (x86)\Windows Kits\10\References\Windows.Devices.Scanners.ScannerDeviceContract\1.0.0.0" -additionalAssemblyPath="C:\Program Files (x86)\Windows Kits\10\References\Windows.Devices.Sms.LegacySmsApiContract\1.0.0.0" -additionalAssemblyPath="C:\Program Files (x86)\Windows Kits\10\References\Windows.Gaming.Preview.GamesEnumerationContract\1.0.0.0" -additionalAssemblyPath="C:\Program Files (x86)\Windows Kits\10\References\Windows.Globalization.GlobalizationJapanesePhoneticAnalyzerContract\1.0.0.0" -additionalAssemblyPath="C:\Program Files (x86)\Windows Kits\10\References\Windows.Management.Deployment.Preview.DeploymentPreviewContract\1.0.0.0" -additionalAssemblyPath="C:\Program Files (x86)\Windows Kits\10\References\Windows.Management.Orchestration.OrchestrationContract\1.0.0.0" -additionalAssemblyPath="C:\Program Files (x86)\Windows Kits\10\References\Windows.Management.Workplace.WorkplaceSettingsContract\1.0.0.0" -additionalAssemblyPath="C:\Program Files (x86)\Windows Kits\10\References\Windows.Media.Capture.AppCaptureContract\3.0.0.0" -additionalAssemblyPath="C:\Program Files (x86)\Windows Kits\10\References\Windows.Media.Capture.CameraCaptureUIContract\1.0.0.0" -additionalAssemblyPath="C:\Program Files (x86)\Windows Kits\10\References\Windows.Media.Devices.CallControlContract\1.0.0.0" -additionalAssemblyPath="C:\Program Files (x86)\Windows Kits\10\References\Windows.Media.MediaControlContract\1.0.0.0" -additionalAssemblyPath="C:\Program Files (x86)\Windows Kits\10\References\Windows.Media.Playlists.PlaylistsContract\1.0.0.0" -additionalAssemblyPath="C:\Program Files (x86)\Windows Kits\10\References\Windows.Media.Protection.ProtectionRenewalContract\1.0.0.0" -additionalAssemblyPath="C:\Program Files (x86)\Windows Kits\10\References\Windows.Networking.NetworkOperators.LegacyNetworkOperatorsContract\1.0.0.0" -additionalAssemblyPath="C:\Program Files (x86)\Windows Kits\10\References\Windows.Networking.Sockets.ControlChannelTriggerContract\2.0.0.0" -additionalAssemblyPath="C:\Program Files (x86)\Windows Kits\10\References\Windows.Perception.Automation.Core.PerceptionAutomationCoreContract\1.0.0.0" -additionalAssemblyPath="C:\Program Files (x86)\Windows Kits\10\References\Windows.Security.EnterpriseData.EnterpriseDataContract\3.0.0.0" -additionalAssemblyPath="C:\Program Files (x86)\Windows Kits\10\References\Windows.Security.ExchangeActiveSyncProvisioning.EasContract\1.0.0.0" -additionalAssemblyPath="C:\Program Files (x86)\Windows Kits\10\References\Windows.Services.Maps.GuidanceContract\2.0.0.0" -additionalAssemblyPath="C:\Program Files (x86)\Windows Kits\10\References\Windows.Services.Maps.LocalSearchContract\3.0.0.0" -additionalAssemblyPath="C:\Program Files (x86)\Windows Kits\10\References\Windows.System.Profile.SystemManufacturers.SystemManufacturersContract\1.0.0.0" -additionalAssemblyPath="C:\Program Files (x86)\Windows Kits\10\References\Windows.System.Profile.ProfileRetailInfoContract\1.0.0.0" -additionalAssemblyPath="C:\Program Files (x86)\Windows Kits\10\References\Windows.System.UserProfile.UserProfileContract\1.0.0.0" -additionalAssemblyPath="C:\Program Files (x86)\Windows Kits\10\References\Windows.System.UserProfile.UserProfileLockScreenContract\1.0.0.0" -additionalAssemblyPath="C:\Program Files (x86)\Windows Kits\10\References\Windows.UI.ApplicationSettings.ApplicationsSettingsContract\1.0.0.0" -additionalAssemblyPath="C:\Program Files (x86)\Windows Kits\10\References\Windows.UI.Core.AnimationMetrics.AnimationMetricsContract\1.0.0.0" -additionalAssemblyPath="C:\Program Files (x86)\Windows Kits\10\References\Windows.UI.Core.CoreWindowDialogsContract\1.0.0.0" -additionalAssemblyPath="C:\Program Files (x86)\Windows Kits\10\References\Windows.UI.Xaml.Hosting.HostingContract\1.0.0.0" -additionalAssemblyPath="C:\Program Files (x86)\Windows Kits\10\References\Windows.Web.Http.Diagnostics.HttpDiagnosticsContract\2.0.0.0" -additionalAssemblyPath="C:\Program Files (x86)\Windows Kits\10\References\Windows.System.SystemManagementContract\2.0.0.0" -additionalAssemblyPath="C:\Program Files (x86)\Windows Kits\10\References\Windows.ApplicationModel.Calls.CallsPhoneContract\3.0.0.0" -additionalAssemblyPath="C:\Program Files (x86)\Windows Kits\10\References\Windows.ApplicationModel.CommunicationBlocking.CommunicationBlockingContract\2.0.0.0" -additionalAssemblyPath="C:\Program Files (x86)\Windows Kits\10\References\Windows.Devices.SmartCards.SmartCardBackgroundTriggerContract\2.0.0.0" -additionalAssemblyPath="C:\Program Files (x86)\Windows Kits\10\References\Windows.Devices.SmartCards.SmartCardEmulatorContract\3.0.0.0" -additionalAssemblyPath="C:\Program Files (x86)\Windows Kits\10\References\Windows.Embedded.DeviceLockdown.DeviceLockdownContract\1.0.0.0" -additionalAssemblyPath="C:\Program Files (x86)\Windows Kits\10\References\Windows.Networking.NetworkOperators.NetworkOperatorsFdnContract\1.0.0.0" -additionalAssemblyPath="C:\Program Files (x86)\Windows Kits\10\References\Windows.Phone.PhoneContract\1.0.0.0" -additionalAssemblyPath="C:\Program Files (x86)\Windows Kits\10\References\Windows.Phone.StartScreen.DualSimTileContract\1.0.0.0" -additionalAssemblyPath="C:\Program Files (x86)\Windows Kits\10\References\Windows.UI.WebUI.Core.WebUICommandBarContract\1.0.0.0".
Symbols will be read from Temp\StagingArea\Data\Managed\UnityEngine.pdb
Symbols will be read from Temp\StagingArea\Data\Managed\Newtonsoft.Json.dll.mdb
Weaving assembly C:\Users\espositd.DSTCORFAX\Downloads\origami-master\Temp\StagingArea\Data\Managed\Newtonsoft.Json.dll
 + Newtonsoft.Json.JsonException
 + Newtonsoft.Json.JsonReaderException
 + Newtonsoft.Json.JsonSerializationException
 + Newtonsoft.Json.JsonWriterException
Will export symbols of pdb format
Mono.Cecil.ResolutionException: Failed to resolve System.Runtime.Serialization.Formatters.FormatterAssemblyStyle
   at Mono.Cecil.Mixin.CheckedResolve(TypeReference self)
   at Mono.Cecil.MetadataBuilder.GetConstantType(TypeReference constant_type, Object constant)
   at Mono.Cecil.MetadataBuilder.AddConstant(IConstantProvider owner, TypeReference type)
   at Mono.Cecil.MetadataBuilder.AddField(FieldDefinition field)
   at Mono.Cecil.MetadataBuilder.AddFields(TypeDefinition type)
   at Mono.Cecil.MetadataBuilder.AddType(TypeDefinition type)
   at Mono.Cecil.MetadataBuilder.AddTypeDefs()
   at Mono.Cecil.MetadataBuilder.BuildTypes()
   at Mono.Cecil.MetadataBuilder.BuildModule()
   at Mono.Cecil.ModuleWriter.<BuildMetadata>b__0(MetadataBuilder builder, MetadataReader _)
   at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TItem item, Func`3 read)
   at Mono.Cecil.ModuleWriter.WriteModuleTo(ModuleDefinition module, Stream stream, WriterParameters parameters)
   at Mono.Cecil.ModuleDefinition.Write(String fileName, WriterParameters parameters)
   at usw.Weaver.WeaveAssembly(String assemblyPath, AssemblyDefinition unityEngineAssemblyDefinition, ReaderParameters readerParameters)
   at usw.Weaver.Weave()
   at usw.Program.RunProgram(ConversionOptions options)
   at usw.Program.Main(String[] args)

PostProcessWinRT.RunSerializationWeaver () (at C:/buildslave/unity/build/PlatformDependent/WinRT/SharedSources/CSharp/PostProcessWinRT.cs:465)
PostProcessWinRT.Process () (at C:/buildslave/unity/build/PlatformDependent/WinRT/SharedSources/CSharp/PostProcessWinRT.cs:123)
UnityEditor.Metro.BuildPostprocessor.PostProcess (BuildPostProcessArgs args) (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/ExtensionModule.cs:130)
UnityEditor.PostprocessBuildPlayer.Postprocess (BuildTarget target, System.String installPath, System.String companyName, System.String productName, Int32 width, Int32 height, System.String downloadWebplayerUrl, System.String manualDownloadWebplayerUrl, BuildOptions options, UnityEditor.RuntimeClassRegistry usedClassRegistry, UnityEditor.BuildReporting.BuildReport report) (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/PostprocessBuildPlayer.cs:176)
UnityEditor.HostView:OnGUI()
