### ISSUE TITLE
 Failed to resolve base type System.Tuple2<T1,T2>

### ISSUE THREAD

**Issue by flyinb** [SaladLab/Json.Net.Unity3D#3]
WEB_GL build in unity, using the Lite version:

> stdout:
> ERROR: Failed to resolve base type System.Tuple`2<T1,T2> for type System.Xaml.Schema.ReferenceEqualityTuple`2
> Fatal error in Mono CIL Linker
> System.Exception: ERROR: Failed to resolve base type System.Tuple`2<T1,T2> for type System.Xaml.Schema.ReferenceEqualityTuple`2
>    at UnusedBytecodeStripper2.ResolveFromMonoBehaviours.IsMonoBehaviourOrScriptableObject(TypeDefinition type)
>    at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
>    at UnusedBytecodeStripper2.ResolveFromMonoBehaviours.Process(LinkContext context)
>    at Mono.Linker.Pipeline.Process(LinkContext context)
>    at Mono.Linker.Driver.RunDriver(Driver driver)
> stderr:

**Comment by flyinb** [comment]
was actually my bad.
